#index:
#    path: /
#    controller: App\Controller\DefaultController::index
add_comment:
    path: add-comment
    controller: App\Infrastructure\Controller\AddCommentController
corona:
    path: corona
    controller: App\Infrastructure\Controller\Corona\CoronaController